### ISSUE TITLE
Which version was used by T1 legion?

### ISSUE THREAD

**Issue by artyom-tarasenko** [gco/sparc-hypervisor#1]
Do you by any chance remember which version was used by the legion emulator distributed with T1? I guess it must be somewhere before T1_REL_1_2_0, but probably even earlier.

It would be nice to build it for qemu. I guess the T2_REL_xxx releases won't work, because qemu has just one partition, and it would be nice to know what release can be used as a starting point.

**Comment by gco** [comment]
It should've been the last T1 version?  But any should work.   The hypervisor adds new platforms (ontario [T1], erie [T1], huron [T2]) and variants (debug, legion, release, etc) so you can build any of those combinations.

That said, I'm not able to reproduce the q.bin from the S10 image directory from the hypervisor sources provided along with it.  I'm still trying to figure that out.

> qemu has just one partition

That shouldn't be relevant for qemu _at this point in time_, it only supports a single target strand right now anyways, right?  The T2 releases are for the T2 processor, supporting more than a single partition is something entirely separate.  Both T1 and T2 have the same hardware partitioning support.

Changes in what's expected in the HVMD (Hypervisor Machine Description) may be troublesome.

**Comment by gco** [comment]
If you're building on Solaris 11 or later, the linker changed behavior and the mapfiles need to explicitly order the .text segment first:

```
# order .text segment first
rom | .text ;
```

before the `bss = ;` line.  Otherwise the `.rodata` section is placed before `.text` and the traptable is in the wrong place.
